name: Cypress Responsiveness Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests in Chrome
        env:
          CYPRESS_BROWSER: chrome
        run: npx cypress run --browser chrome

      - name: Commit and push screenshots
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          mkdir -p cypress/screenshots/chrome
          git add cypress/screenshots
          git commit -m "Add Cypress screenshots for responsiveness tests"
          git push
        continue-on-error: true
