name: Cypress Responsiveness Test for Microsoft Edge

on:
  workflow_dispatch: # Trigger manually from GitHub UI

jobs:
  run-cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests in Microsoft Edge
        env:
          CYPRESS_BROWSER: edge
        run: npx cypress run --browser edge

      - name: Commit and push screenshots
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          mkdir -p cypress/screenshots/edge
          git add cypress/screenshots
          git commit -m "Add Cypress screenshots for Microsoft Edge responsiveness tests"
          git push
        continue-on-error: true
