name: Run Cypress Tests on Multiple Browsers

permissions:
  contents: write

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run_tests:
    strategy:
      matrix:
        browser: [chrome]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.BOTTOKEN }}

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: |
        npm ci  # Install dependencies from package-lock.json
  
    
    - name: Install Cypress
      run: npm install cypress --save-dev  # Install Cypress as a dev dependency

    - name: Run Cypress tests
      run: npx cypress run --spec 'cypress/e2e/'  # Runs all tests in the e2e folder

    

    - name: Run Cypress Tests on ${{ matrix.browser }}
      env:
        BROWSER: ${{ matrix.browser }}
      run: |
        npx cypress run --browser $BROWSER --headless

    - name: Upload Screenshots for ${{ matrix.browser }}
      uses: actions/upload-artifact@v4
      with:
        name: screenshots-${{ matrix.browser }}
        path: cypress/screenshots
